name: "Build Emacs with packages"

on:
  push:
    branches:
      - master
    paths:
      - modules/macintosh.nix
      - flake.*
      - .github/**

  schedule:
    - cron: '00 00 * * *'

jobs:
  build-emacs-with-pkgs:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:

    - uses: actions/checkout@v2.3.4
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
 
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - uses: cachix/cachix-action@v10
      with:
        name: cmacrae
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: >-
        nix show-derivation
        .#darwinConfigurations.macbook.config.home-manager.users.cmacrae.programs.emacs.finalPackage
        > emacs.drv

    - uses: actions/cache@v2
      id: cache-drv
      with:
        path: ./emacs.drv
        key: emacs-drv-${{ hashFiles('emacs.drv') }}

    - run: >-
        nix build
        .#darwinConfigurations.macbook.config.home-manager.users.cmacrae.programs.emacs.finalPackage
      if: steps.cache-drv.outputs.cache-hit != 'true'

    - run: >-
        nix log
        $(nix show-derivation
        .#darwinConfigurations.macbook.config.home-manager.users.cmacrae.programs.emacs.finalPackage
        | jq -r '.|keys[0]')
        > emacs-build.log
      if: ${{ failure() }}

    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: emacs-build.log
        path: emacs-build.log
